# MPC params
N_sample: 5
H_mpc: 3
H_sim: 320
κ_mpc: 2.0e-4

# IP options 
κ_mpc_ip: 2.0e-4
r_tol_ip: 1.0e-5
undercut_ip: 5.0e-0
max_time_ip: 1.0e+5
# Newton options
r_tol_nt: 3.0e-5
max_time_nt: 1.0e-1
max_iter_nt: 5

# velocity v
w_v_pos_x: 1.0e-0
w_v_pos_y: 1.0e-0
w_v_pos_z: 1.0e-0
w_v_ang_z: 6.0e+3
w_v_ang_y: 6.0e+3
w_v_ang_x: 1.0e+3
w_v_ft_x: 1.0e-0
w_v_ft_y: 1.0e-0
w_v_ft_z: 1.0e-0

# position q
w_q_pos_x: 0
w_q_pos_y: 0
w_q_pos_z: 5.0e-0
w_q_ang_z: 1.0e+3
w_q_ang_y: 1.0e+3
w_q_ang_x: 1.0e-1
w_q_ft_x: 2.0e-1
w_q_ft_y: 2.0e-1
w_q_ft_z: 1.0e-0

# control u
w_u_1: 3.0e-3
w_u_2: 3.0e-3
w_u_3: 3.0e-3

# v_target
v0: 0


# ref
# ref_path: ""