# MPC params
N_sample: 5
H_mpc: 3
H_sim: 320
κ_mpc: 1.0e-4

# IP options 
κ_mpc_ip: 1.0e-5
r_tol_ip: 1.0e-5
undercut_ip: 5.0e-0
max_time_ip: 1.0e+5
# Newton options
r_tol_nt: 3.0e-5
max_time_nt: 1.0e-1
max_iter_nt: 2

# velocity v
w_v_pos_x: 8.0e+2
w_v_pos_y: 3.5e+2
w_v_pos_z: 0.5e+2
w_v_ang_z: 8.0e+3
w_v_ang_y: 7.5e+3
w_v_ang_x: 5.0e+3
w_v_ft_x: 2.3e+1
w_v_ft_y: 2.5e+1
w_v_ft_z: 3.0e+1

# position q
w_q_pos_x: 1.0e+1
w_q_pos_y: 1.0e+1
w_q_pos_z: 0
w_q_ang_z: 4.0e+2
w_q_ang_y: 3.0e+2
w_q_ang_x: 6.0e+2
w_q_ft_x: 1.5e-0
w_q_ft_y: 2.0e-0
w_q_ft_z: 1.5e+1
# control u
w_u_1: 8.0e-3
w_u_2: 8.0e-3
w_u_3: 8.0e-3

# v_target
v0: 0


# ref
# ref_path: ""