# MPC params
N_sample: 5
H_mpc: 20
H_sim: 320
κ_mpc: 1.0e-5

# IP options 
κ_mpc_ip: 1.0e-5
r_tol_ip: 1.0e-5
undercut_ip: 5.0e-0
max_time_ip: 1.0e+5
# Newton options
r_tol_nt: 3.0e-5
max_time_nt: 1.0e-1
max_iter_nt: 5

# velocity v
w_v_pos_x: 4.0e+0
w_v_pos_y: 1.5e+0
w_v_pos_z: 0.5e+0
w_v_ang_z: 7.0e+3
w_v_ang_y: 5.0e+3
w_v_ang_x: 3.0e+3
w_v_ft_x: 2.6e-3
w_v_ft_y: 1.4e-3
w_v_ft_z: 2.0e-3

# position q
w_q_pos_x: 1.0e+1
w_q_pos_y: 1.0e+1
w_q_pos_z: 1.0e+1
w_q_ang_z: 1.2e+2
w_q_ang_y: 6.0e+2
w_q_ang_x: 1.2e+2
w_q_ft_x: 5.0e+1
w_q_ft_y: 5.0e+1
w_q_ft_z: 38.5e+1

# control u
w_u_1: 8.0e-3
w_u_2: 8.0e-3
w_u_3: 1.0e-3

# v_target
v0: 0


# ref
# ref_path: ""